version: '3'

services:

  tgbd:
    ports:
      - 8000:8080
    build:
      context: ./TgBd
    container_name: tgbd
    environment:
      spring.datasource.url: jdbc:postgresql://data:5432/usertg
      spring.datasource.username: memo
      spring.datasource.password: memobot
      spring.kafka.bootstrap-servers: kafka:9092
    depends_on:
      - data
      - kafka

  tgservice:
    build:
      context: ./TgService
    container_name: tgservice
    ports:
      - 8010:8090
    restart: unless-stopped
    environment:
      spring.kafka.bootstrap-servers: kafka:9092
    depends_on:
      - tgbd
      - kafka

  data:
    image: postgres:latest
    container_name: data
    restart: always
    environment:
      POSTGRES_USER: memo
      POSTGRES_PASSWORD: memobot
      POSTGRES_DB: usertg
      POSTGRES_SCHEMA: members
      STOP_ON_MIGRATION_FAILURE: "false"
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/pgdata
    healthcheck:
      test: PGPASSWORD=memobot psql -d usertg -U memo -w -c '\q'
      interval: 20s
      timeout: 10s


  # Kafka ---------------------------------------------------------------------
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/kafka

volumes:
  db-data:
    external: false
  kafka-data:
    external: false
  zookeeper-data:
    external: false